Backup/Django_Youtube/demo_form/demo_form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/',include('news.urls'))
]

Backup/Django_Youtube/demo_form/news/urls.py
from django.urls import path, include
from . import views

app_name = 'news'
urlpatterns = [
    #class base view
    path('', views.IndexClass.as_view(), name='index'),
    # path('add/', views.PostClass.as_view(), name='add'),
    path('save/', views.SaveNewClass.as_view(), name='save'),
    path('email/', views.EmailViewClass.as_view(), name='email'),
    path('process/',views.ProcessClass.as_view(), name='process')
]

Backup/Django_Youtube/demo_form/news/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField(max_length=1000,blank=False, null=False)
    time_create = models.DateTimeField(default=timezone.datetime.now())

    def __str__(self):
        return self.title

Backup/Django_Youtube/demo_form/news/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content', 'time_create',)
        widget = {
            'title': forms.TextInput(attrs={'class':'form-input'}),
        }

class SendEmail(forms.Form):
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-input'}))
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-input', 'id':'custom-form'}))
    cc = forms.BooleanField(required=False)

Backup/Django_Youtube/demo_form/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PostForm, SendEmail
from django.views import View
# Create your views here.

#Class base view
class IndexClass(View):
    def get(self, request):
        return HttpResponse('hello world!')

class SaveNewClass(View):
    def get(self, request):
        a = PostForm()
        return render(request,('news/add-news.html'),{'f':a})

    def post(self, request):
        g = PostForm(request.POST)
        if g.is_valid():
            g.save()
            return HttpResponse('SAVE SUCCESS')
        else:
            return HttpResponse('Form is not valid')

class EmailViewClass(View):
    def get(self, request):
        b = SendEmail()
        return render(request, ('news/email.html'),{'f':b})

class ProcessClass(View):
    def post(self, request):
        g = SendEmail(request.POST)
        if g.is_valid():
            title = g.cleaned_data['title']
            content = g.cleaned_data['content']
            cc = g.cleaned_data['cc']
            email = g.cleaned_data['email']
            context = {
                'title':title,
                'content':content,
                'cc':cc,
                'email':email,
            }
            return render(request,('news/print-email.html'),context)
        else:
            return HttpResponse('Form not validate')

    

Backup/Django_Youtube/demo_form/news/templates/news/add-news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'news:save' %}" method="POST">
        {% csrf_token %}
        
        {{ f.title }}<br/>
        {{ f.content }}<br/>
        {{ f.time_create}} <br/>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

Backup/Django_Youtube/demo_form/news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'news:process' %}" method="POST">
        {% csrf_token %}
        {{f.title}}<br/>
        {{f.email}}<br/>
        {{f.content}}<br/>
        {{f.cc}}<br/>
        <input type="submit" value="Send Email">
    </form>
</body>
</html>

Backup/Django_Youtube/demo_form/news/templates/news/print-email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        td{
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <table>
        <tr>
            <td>Title</td>
            <td>Content</td>
            <td>Email</td>
            <td>CC</td>
        </tr>
        <tr>
            <td>{{title}}</td>
            <td>{{content}}</td>
            <td>{{email}}</td>
            <td>{{cc}}</td>
        </tr>
    </table>
</body>
</html>