Backup/Django_Youtube/Authen/Authen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('Login.urls'))
]

Backup/Django_Youtube/Authen/Login/urls.py
from django.urls import path, include
from . import views

app_name = 'Login'
urlpatterns = [
    path('', views.IndexClass.as_view(), name='index'),
    path('login/', views.LoginClass.as_view(), name='login'),
    path('user-view/', views.ViewUserAuthen.as_view(), name='user-view'),
    path('view-product/', views.view_product, name='view-product'),
    path('add-post', views.AddPost.as_view(), name='add-post')
]

Backup/Django_Youtube/Authen/Login/models.py
from django.db import models
#Custom user model
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.CharField(max_length=255)

    def __str__(self):
        return self.title

class MyUser(AbstractUser):
    sex_choice = ((0,'Male'), (1,'Female'))
    age = models.IntegerField(default=0)
    sex = models.IntegerField(choices=sex_choice, default=0)
    address = models.CharField(default='', max_length=255)

Backup/Django_Youtube/Authen/Login/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content',]

Backup/Django_Youtube/Authen/Login/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, decorators
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm
# Create your views here.

class IndexClass(View):
    def get(self, request):
        return HttpResponse('<h1>Login</h1>')

class LoginClass(View):
    def get(self, request):
        return render(request, ('Login/login.html'))

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')

        my_user = authenticate(username=username, password=password)
        if my_user is None:
            return HttpResponse('User not exist!')

        login(request,my_user)
        return render(request,('Login/success.html'))

class ViewUserAuthen(LoginRequiredMixin,View):
    login_url='/login/login'
    def get(self,request):
        return HttpResponse('<h1>This is my page of you</h1>')
    
@decorators.login_required(login_url='/login/login')
def view_product(request):
    return HttpResponse('View product')


class AddPost(LoginRequiredMixin, View):
    login_url='/login/login'

    def get(self, request):
        f = PostForm
        context = {'fm':f}
        return render(request,('Login/add-post.html'),context)

    def post(self, request):
        f = PostForm(request.POST)
        if not f.is_valid():
            return HttpResponse('Form not valid')
        
        if request.user.has_perm('Login.add_post'):
            f.save()
        else:
            return HttpResponse('You not have permisson')

        return HttpResponse('ADD POST OK')

Backup/Django_Youtube/Authen/Login/templates/Login/add-post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'Login:add-post' %}" method="POST">
        {% csrf_token %}
        {{fm}}
        <input type="submit" value="Add Post">
    </form>
</body>
</html>

Backup/Django_Youtube/Authen/Login/templates/Login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="login">
        <form action="" method="POST">
            {% csrf_token %}
            <input type="text" name="username">
            <input type="password" name="password">
            <input type="submit">
        </form>
    </div>
</body>
</html>

Backup/Django_Youtube/Authen/Login/templates/Login/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login Successfully</h1>
</body>
</html>