Backup/Django_Youtube/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

Backup/Django_Youtube/mysite/polls/urls.py
from django.urls import path
from . import views

#Url namespace
app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.viewListQuestion, name='question'),
    path('detail/<int:question_id>', views.detailView, name='detail'),
    path('<int:question_id>', views.vote, name='vote')
]

Backup/Django_Youtube/mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=255)
    time_public = models.DateTimeField()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    vote = models.IntegerField(default=0)

Backup/Django_Youtube/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Question, Choice

#Fucntion base View
def index(request):
    myname='DuyNND'
    item = ['Macbook', 'iPhone', 'EXCITER','handsome']
    context={"name":myname, "items":item}
    return render(request,('polls/index.html'),context)

def viewListQuestion(request):
    list_questions = Question.objects.all()
    # list_questions = get_object_or_404(Question,pk=5)
    context = {'list_request': list_questions}
    return render(request, ('polls/question_list.html'),context)

def detailView(request, question_id):
    q = Question.objects.get(pk=question_id)
    context = {'qs':q}
    return render(request,('polls/detail_question.html'),context)

def vote(request, question_id):
    q = Question.objects.get(pk=question_id)
    # Lay param tren url
    try:
        data = request.POST['choice']
        c = q.choice_set.get(pk=data)
    except:
        return HttpResponse("Error")
    c.vote = c.vote + 1
    c.save()
    context = {'q':q}
    return render(request, ('polls/result.html'), context)

Backup/Django_Youtube/mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div class="header">
        <h1>WEBSITE</h1>
    </div>
    <div class="menu">
        <ul>
            <li>ITEM 1</li>
            <li>ITEM 2</li>
            <li>ITEM 3</li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>

Backup/Django_Youtube/mysite/polls/templates/polls/detail_question.html
{% extends 'polls/base.html' %}

{% block content %}
{% if qs %}
<h1>{{qs.question_text}}</h1>
<form action="{% url 'polls:vote' qs.id %}" method="POST">
    {% csrf_token %}
    <ul>
        {% for item in qs.choice_set.all %}
        <li>
            <input type="radio" value="{{item.id}}" name="choice">
            {{item.choice_text}}
        </li>
        {% endfor %}
        <p><input type="submit" value="Submit"></p>
    </ul>
</form>

{% endif %}
{% endblock%}

Backup/Django_Youtube/mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
<h1>Template polls</h1>
<p>Hello world!</p>
<p>My name: <b>{{name}}</b></p>
<p>My product:</p>
<ul>
    {% for item in items %}
    {% if item != 'handsome' %}
    <li>{{item}}</li>
    {% endif %}
    {% endfor %}
</ul>
{% endblock %}

Backup/Django_Youtube/mysite/polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}

{% block content %}
{% if list_request%}
{% for item in list_request %}
<a href="{% url 'polls:detail' item.id %}">
    <h3>{{item.question_text}}</h3>
</a>
{% endfor %}
{% else %}
<h3 style="color: red;">No item question</h3>
{% endif %}
{% endblock%}

Backup/Django_Youtube/mysite/polls/templates/polls/result.html
{% extends 'polls/base.html' %}

{% block content %}
{% if q %}
<h1>{{q.question_text}}</h1>
<p>Result:</p>
{% for item in q.choice_set.all %}
    <p>{{item.choice_text}}: {{item.vote}}</p>
{% endfor %}
<a href="{% url 'polls:question' %}">Vote continue</a>
{% endif %}
{% endblock %}